[package]
name = "pdf-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
colourful-logger = "2.0.1"
file-format = "0.28.0"
hayro = "0.4.0"
hayro-interpret = "0.4.0"
hayro-svg = "0.2.0"
log = "0.4.28"
